web-service/webumvral/web/urls.py
from django.urls import path, re_path
from . import views
from .views import CourseListJson, StudentListJson
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

app_name="web"
handler404 = "web.views.404"

urlpatterns = [
    re_path(r'home/$', views.home, name='home'),
    re_path(r'logout/$', views.logout_method, name='logout'),
    re_path(r'login/$', views.login_method, name='login'),
    re_path(r'register/$', views.register, name='register'),
    re_path(r'course/list$', views.courses_list, name='course_list'),
    re_path(r'course/create/$', views.course_edit, name='course_create'),
    re_path(r'course/edit/$', views.course_edit, name='course_edit'),
    re_path(r'course/edit/(?P<course>\w+)$', views.course_edit, name='course_edit'),
    re_path(r'course/delete/$', views.course_delete, name='course_delete'),
    re_path(r'course/delete/(?P<course>\w+)$', views.course_delete, name='course_delete'),
    re_path(r'course/read/(?P<course>\w+)$', views.course_read, name='course_read'),
    re_path(r'course/read/(?P<course>\w+)/students/$', views.course_students, name='course_students'),
    re_path(r'course/read/(?P<course>\w+)/students/invite$', views.course_invite, name='course_invite'),
    re_path(r'course/read/(?P<course>\w+)/students/(?P<student_id>\w+)/ban$', views.course_ban, name='course_ban'),
    re_path(r'course/read/(?P<course>\w+)/students/(?P<student_id>\w+)$', views.studentCourseProfile, name='student_courseprofile'),
    re_path(r'course/api/(?P<course>\w+)/(?P<student_id>\w+)$', views.getStudentResultData, name='student_getdata'),
    re_path(r'course/api/(?P<course>\w+)/(?P<student_id>\w+)/(?P<exp_id>\w+)$', views.getStudentResultData, name='student_getdata'),
    url(r'^my/datatable/data/stud$', login_required(StudentListJson.as_view()), name='course_student_list_json'),
    re_path(r'course/read/(?P<course>\w+)/experiences/$', views.course_experience, name='course_experience'),
    re_path(r'course/read/(?P<course>\w+)/experiences/(?P<experience>\w+)$', views.course_exp_visibility, name='course_exp_visibility'),
    re_path(r'course/read/(?P<course>\w+)/experiences/(?P<experience>\w+)/test$', views.experience_test, name='experience_test'),
    re_path(r'course/read/(?P<course>\w+)/experiences/(?P<experience>\w+)/test/edit$', views.experience_test_edit, name='experience_test_edit'),
    re_path(r'course/read/(?P<course>\w+)/experiences/(?P<experience>\w+)/test/visibility$', views.experience_test_visibility, name='experience_test_visibility'),
    re_path(r'course/read/(?P<course>\w+)/experiences/(?P<experience>\w+)/test/delete$', views.experience_test_delete, name='experience_test_delete'),
    url(r'^my/datatable/data/$', login_required(CourseListJson.as_view()), name='course_list_json'),
    re_path(r'404/$', views.page404, name='404'),
    re_path(r'user/(?P<client_id>\d+)/profile/$', views.profile, name='profile'),
    re_path(r'user/(?P<client_id>\d+)/profile/edit$', views.profile_edit, name='profile_edit'),
    re_path(r'user/(?P<client_id>\d+)/inbox/(?P<inbox_type>\d+)/$', views.message_view, name='msg_view'),
    re_path(r'user/(?P<client_id>\d+)/inbox/message/(?P<msg_id>\d+)/(?P<action>\d+)$', views.msg_actions, name='msg_actions'),
    re_path(r'user/(?P<client_id>\d+)/inbox/message/direct$', views.msg_direct, name='msg_direct'),
    re_path(r'support/$', views.support, name='support'),
    re_path(r'support/exp$', views.send_experience, name='support_experience'),
    re_path(r'course/read/(?P<course>\w+)/experiences/video/$', views.experience_video, name="video"),
    re_path(r'course/read/(?P<course>\w+)/experiences/(?P<expcourse>\w+)/delete/$', views.delexpcourse, name="delexpcourse"),
    re_path(r'user/(?P<client_id>\d+)/experiences/$', views.myexperiences, name="myexps"),
    re_path(r'user/(?P<client_id>\d+)/experiences/add$', views.addexperiences, name="addexps"),
    re_path(r'user/(?P<client_id>\d+)/experiences/(?P<ava_id>\d+)/edit$', views.editexperiences, name="editexps"),
    re_path(r'user/(?P<client_id>\d+)/experiences/(?P<ava_id>\d+)/delete$', views.delexperiences, name="delexps"),
    re_path(r'user/(?P<client_id>\d+)/expcourse/(?P<expcourse>\d+)/date$', views.datepicker, name="date"),
]

web-service/webumvral/webumvral/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from tastypie.api import Api
from api.resources import ExperienceResource
from api.resources import MessageResource
from api.resources import ExpdispResource
from api.resources import ClientResource
from api.resources import StudentResource
from api.login import UserResource
from api.resources import CourseResource
from api.resources import ExpcourseResource
from api.resources import MetricResource

experience = ExperienceResource()
message = MessageResource()
expdisp = ExpdispResource()
user = UserResource()
client = ClientResource()
student = StudentResource()
course = CourseResource()
expcourse = ExpcourseResource()
metric = MetricResource()

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('/', include(administration.urls)) TO BE CREATED
    #path('api/', include('api.urls')),
    path('web/', include('web.urls')),
    url(r'^api/', include(experience.urls)),
    url(r'^api/', include(message.urls)),
    url(r'^api/', include(expdisp.urls)),
    url(r'^api/', include(user.urls)),
    url(r'^api/', include(client.urls)),
    url(r'^api/', include(student.urls)),
    url(r'^api/', include(course.urls)),
    url(r'^api/', include(expcourse.urls)),
    url(r'^api/', include(metric.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-service/webumvral/web/forms.py
from django import forms

class SupportForm(forms.Form):
    nombre = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    mensaje = forms.CharField(
        max_length=5000,
        widget=forms.Textarea(),
        help_text='Escribe tu mensaje.'
    )

    def clean(self):
        cleaned_data = super(SupportForm, self).clean()
        nombre = cleaned_data.get('name')
        email = cleaned_data.get('email')
        mensaje = cleaned_data.get('message')
        if not nombre and not email and not mensaje:
            raise forms.ValidationError('Tienes que escribir algo!')

class ExperienceForm(forms.Form):

    nombre = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    nombre_experiencia = forms.CharField(max_length=254)
    nivel = forms.CharField(widget=forms.Select)
    contenido = forms.CharField(widget=forms.Select)
    mensaje = forms.CharField(
        max_length=10000,
        widget=forms.Textarea(),
        help_text='Describe como debe ser tu experiencia.'
    )
    interaccion = forms.CharField(
        max_length=10000,
        widget=forms.Textarea(),
        help_text='Describe como el estudiante realiza la interacción',
        label="Interacción"
    )

    def clean(self):
        cleaned_data = super(ExperienceForm, self).clean()
        nombre = cleaned_data.get('name')
        email = cleaned_data.get('email')
        nombre_experiencia = cleaned_data.get('nombre_experiencia')
        mensaje = cleaned_data.get('message')
        if not nombre and not email and not mensaje:
            raise forms.ValidationError('Tienes que escribir algo!')

web-service/webumvral/web/views/support.py
from django.shortcuts import render, redirect
from .common import get_base_context
from django.contrib.auth.decorators import login_required
from ..models import *
from django.utils.html import escape
from django.http import HttpResponse
from django.core.mail import send_mail
from ..forms import SupportForm, ExperienceForm


@login_required
def support(request):
    context = get_base_context(request)
    context['section'] = 'support'
    if (request.method == "POST"):
        form = SupportForm(request.POST)
        if form.is_valid():
            try:
                nombre = form.cleaned_data['nombre']
                email = form.cleaned_data['email']
                mensaje = form.cleaned_data['mensaje']
                send_mail(
                    '[SOPORTE] - '+nombre+' - '+email,
                    mensaje,
                    email,
                    ['umvralapp@gmail.com'],
                    fail_silently=False,)
                context['enviado'] = True
            except:
                context['enviado'] = False
    context['form'] = SupportForm()
    return render(request, 'web/support.html', context)


@login_required
def send_experience(request):
    context = get_base_context(request)
    context['section'] = 'support'
    if (request.method == "POST"):
        form = ExperienceForm(request.POST)
        if form.is_valid():
            try:
                nombre = form.cleaned_data['nombre']
                nombre_experiencia = form.cleaned_data['nombre_experiencia']
                email = form.cleaned_data['email']
                criterios = form.cleaned_data['nivel'] + ' - ' + form.cleaned_data['contenido']
                mensaje = form.cleaned_data['mensaje']
                inter = form.cleaned_data['interaccion']
                send_mail(
                    '[EXPERIENCIA] - '+nombre+' - '+email,
                    'Nombre Experiencia: '+nombre_experiencia+'\nCriterios: '+criterios+'\n\nDescripción experiencia: \n'+mensaje+'\n\nInteracción experiencia: \n'+inter,
                    email,
                    ['umvralapp@gmail.com'],
                    fail_silently=False,)
                context['enviado'] = True
            except:
                context['enviado'] = False
    context['form'] = ExperienceForm()
    return render(request, 'web/support_experience.html', context)

web-service/webumvral/web/views/video.py
from django.shortcuts import render, redirect
from .common import get_base_context
from ..models import *
from django.http import HttpResponse
from .experience import filter_experiences

def myexperiences(request, client_id):
    context = get_base_context(request)
    context['section'] = 'experience'
    context['client_id'] = client_id
    experiencias = AvailabilityModel.objects.filter(professor__pk=client_id)
    context['experiencias'] = experiencias
    return render(request, 'web/myexps.html', context)

def get_url(string):
    if ('watch?v=' in string):
        return string.split('watch?v=')[1].split('?')[0]
    if ('youtu.be' in string):
        return string.split('be/')[1].split('?')[0]
    return False

def editexperiences(request, client_id, ava_id):
    context = get_base_context(request)
    context['section'] = 'experience'
    context['client_id'] = client_id
    ava = AvailabilityModel.objects.get(pk=ava_id)
    context['ava'] = ava
    if (request.method == "GET"):
        return render(request, 'web/editvideos.html', context)
    if (request.method == "POST"):
        if ((request.POST['video'] == '') or ('youtu' not in request.POST['video'])):
            context['experiences'] = filter_experiences(request.user.profile.pk)
            context['error_2'] = True
            context['Bad'] = True
            return render(request, 'web/editvideos.html', context)
        ava.video = get_url(request.POST['video'])
        ava.save()
        context['Ok'] = True
    return render(request, 'web/editvideos.html', context)

def delexperiences(request, client_id, ava_id):
    context = get_base_context(request)
    context['section'] = 'experience'
    try:
        ava = AvailabilityModel.objects.get(pk=int(ava_id))
        ava.delete()
    except:
        context['fail'] = True
        return redirect('web:myexps', client_id=client_id)
    return redirect('web:myexps', client_id=client_id)

def addexperiences(request, client_id):
    context = get_base_context(request)
    context['section'] = 'experience'
    context['client_id'] = client_id
    experiencias = filter_experiences(client_id)
    context['experiencias'] = experiencias
    if (request.method == "POST"):
        if (request.POST['exp'] == 'None'):
            context['experiences'] = filter_experiences(request.user.profile.pk)
            context['error_1'] = True
        if ((request.POST['video'] == '') or ('youtu' not in request.POST['video'])):
            context['experiences'] = filter_experiences(request.user.profile.pk)
            context['error_2'] = True
        if (("error_1" in context) or ("error_2" in context)):
            return render(request, 'web/videos.html', context)
        ava = AvailabilityModel()
        ava.professor = request.user.profile
        ava.experience = ExperienceModel.objects.get(pk=int(request.POST['exp']))
        ava.video = get_url(request.POST['video'])
        ava.position = len(AvailabilityModel.objects.filter(professor=request.user.profile))
        ava.save()
        return redirect('web:myexps', client_id=client_id)
    return render(request, 'web/videos.html', context)

web-service/webumvral/web/templates/web/course_experience.html
{% extends "web/base_page.html" %}

{% load static %}

{% block title %}
Lista de Experiencias
{% endblock %}

{% block subtitle %}
{% endblock %}

{% block breadcrumb %}
<li>
  <a href="{% url 'web:course_list' %}"><span>Mis Cursos</span></a>
  <i class="fa fa-angle-right"></i>
</li>
<li>
  <a href="{% url 'web:course_read' course_id %}"><span>{{course_name}}</span></a>
  <i class="fa fa-angle-right"></i>
</li>
<li>
  <a href="{% url 'web:course_experience' course_id %}"><span>Lista de Experiencias</span></a>
  <i class="fa fa-angle-right"></i>
</li>
{% endblock %}
{% block page_actions %}
<a href="{% url 'web:video' course_id %}" class="btn btn-default"><i class="fa fa-gamepad"></i> Agregar experiencia</a>
<a id="movement" class="btn btn-info"><i class="fa fa-lock"></i> Activar movimiento</a>
{% endblock %}
{% block content %}
<div class="row">
  <form id="myForm" action="{% url 'web:course_experience' course_id %}" method="post">
    {% csrf_token %}
  <div class="portlet light portlet-fit bordered">
      <div class="portlet-body">
          <div class="table-scrollable table-scrollable-borderless">
              <table id="tablasorteable" class="table table-hover sorted_table">
                  <thead>
                      <tr class="uppercase">
                          <th> </th>
                          <th> Nombre </th>
                          <th> Descripción </th>
                          <th> <center>Video</center> </th>
                          <th> <center>Estado</center> </th>
                          <th> <center>Prueba</center> </th>
                          <th> <center>Acciones</center></th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for exp in experiences  %}
                      <tr>
                        <input type="hidden" name="pos-{{ forloop.counter0 }}" value="{{exp.pk}}">
                        <td> <i class="moveIcon"></i>
                        </td>
                        <td > {{exp.available.experience.name}} </td>
                        <td> {{exp.available.experience.description|truncatechars:50}} </td>
                          <td><center><a href="http://youtube.com/watch?v={{exp.available.video}}" target="_blank"><i class="fa fa-youtube-play fa-2x" style="color:red"></i></a></center></td>
                        <td>
                          <center>
                            {% if exp.visible %}
                            <i class="fa fa-eye" style="color:black"></i>
                            {% else %}
                            <i class="fa fa-eye-slash" style="color:gray"></i>
                            {% endif %}
                          </center>
                       </td>
                       <td>
                         <center>
                          {% if exp.test %}
                          {% if exp.test.visible %}
                            <span class="label label-sm label-success "> Activa </span>
                          {% else %}
                            <span class="label label-sm label-default "> Creada </span>
                          {% endif %}
                          {% else %}
                            <span class="label label-sm label-danger "> Sin crear </span>
                          {% endif %}
                        </center>
                      </td>
                      <td><center>
                        <div class="btn-group">
                          <button class="btn btn-xs orange dropdown-toggle" type="button"
                                  data-toggle="dropdown" aria-expanded="false">
                            ADMINISTRAR
                            <i class="fa fa-angle-down"></i>
                          </button>
                          <ul class="dropdown-menu pull-right" role="menu">
                            <li>
                              <a href="{% url 'web:editexps' request.user.profile.pk exp.available.pk %}">
                              <i class="icon-note"></i> Editar video </a>
                            </li>
                            <li class="divider" role="separator"></li>
                            {% if exp.test %}
                            {% if not exp.test.visible %}
                            <li>
                              <a href="{% url 'web:experience_test_edit' course_id exp.available.experience.pk %}">
                              <i class="icon-note"></i> Editar prueba </a>
                            </li>
                            <li>
                              <a href="{% url 'web:experience_test_delete' course_id exp.available.experience.pk %}">
                              <i class="icon-ban"></i> Eliminar prueba </a>
                            </li>
                            <li class="divider" role="separator"></li>
                            {% endif %}
                            <li>
                              <a href="{% url 'web:experience_test_visibility' course_id exp.available.experience.pk %}">
                              <i class="fa fa-eye"></i> Cambiar visibilidad prueba </a>
                            </li>
                            <li class="divider" role="separator"></li>
                            {% else %}
                            <li>
                              <a href="{% url 'web:experience_test' course_id exp.available.experience.pk %}">
                              <i class="icon-note"></i> Crear prueba </a>
                            </li>
                            <li class="divider" role="separator"></li>
                            {% endif %}
                            <li>
                              <a href="{% url 'web:course_exp_visibility' course_id exp.pk %}">
                              <i class="fa fa-eye"></i> Cambiar visibilidad para el curso</a>
                            </li>
                            <li>
                              <a class="modal-link" data-toggle="modal" name="{{exp.available.experience.name}}" id="{{exp.pk}}"> 
                              <i class="fa fa-calendar"></i> Agregar fecha de visibilidad</a>
                            </li>
                            <li class="divider" role="separator"></li>
                            <li>
                              <a href="{% url 'web:delexpcourse' course_id exp.pk %}">
                              <i class="icon-ban"></i> Eliminar experiencia del curso </a>
                            </li>
                          </ul>
                        </div></center>
                      </td>
                    {% endfor %}
                  </tbody>
              </table>
              <br><br><br><br><br><br><br><br><br><br>
          </div>
      </div>
  </div>
</div>
</form>
</div>
<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title" id="mtitle">Modal Title</h4>
            </div>
            <form id="dateform" action="{% url 'web:date' request.user.profile.pk 9999999 %}" method="POST">
              {% csrf_token %}
            <div class="row modal-body"> 
                <div class="row form-group">
                  <div class="col-md-3"></div>
                  <div class="input-group input-medium date date-picker" data-date-format="yyyy-mm-dd" data-date-start-date="+0d">
                      <input name="dateselected" type="text" class="form-control" readonly="">
                      <span class="input-group-btn">
                          <button class="btn default" type="button">
                              <i class="fa fa-calendar"></i>
                          </button>
                      </span>
                  </div>
                </div>
                <input type="hidden" name="dateid" id="dateid" value="">
            </div>
            <div class="row modal-footer">
                <div class="col-md-3"></div>
                <div class="col-md-3"><button type="submit" class="btn green">Asignar fecha</button></div>
                <div class="col-md-3"><button type="button" class="btn dark btn-outline" data-dismiss="modal">Cerrar</button></div>
                <div class="col-md-3"></div>
            </div>
          </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
{% endblock %}
{% block plugin_js %}
<script type="text/javascript" src="{% static 'web/global/plugins/jquery-sortable/jquery-sortable.js' %}"></script>
<script src="{% static 'web/pages/scripts/components-date-time-pickers.min.js' %}" type="text/javascript"></script>
<script src="{% static 'web/global/plugins/moment.min.js' %}" type="text/javascript"></script>
<script src="{% static 'web/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js' %}" type="text/javascript"></script>
<script src="{% static 'web/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
<script src="{% static 'web/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}" type="text/javascript"></script>
<script src="{% static 'web/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>
<script src="{% static 'web/global/plugins/clockface/js/clockface.js' %}" type="text/javascript"></script>
<script>
$(document).ready(function(){
  var activar = '<i class="fa fa-lock"></i> Activar movimiento';
  var desactivar = '<i class="fa fa-unlock"></i> Guardar cambios';
  var sorteable = "table table-hover sorted_table";
  var unsorteable = "table table-hover";
  var active_color = "btn btn-info";
  var deactive_color = "btn btn-danger";
  $('.sorted_table').sortable({
  containerSelector: 'table',
  itemPath: '> tbody',
  itemSelector: 'tr',
  placeholder: '<tr><td><td><br></td></td> <td></td> <td> </td></tr>',
  });
  $('.sorted_table').sortable('disable');
  var classname = document.getElementsByClassName("modal-link");
  console.log(classname);
  for (var i = 0; i < classname.length; i++) {
    console.log(classname[i]);
    classname[i].addEventListener('click',function(){
      $('#mtitle')[0].innerHTML = "Fecha visible para: " + this.name;
      $('#dateid')[0].value = this.id;
      $('#dateform')[0].action = $('#dateform')[0].action.replace('9999999',this.id)
      $('#basic').modal('toggle');
    });
  }
  $('#movement').click(function(){
    if ($('#movement')[0].innerHTML == activar){
      for (var i=0; i < $('.moveIcon').length; i++){
        $('.moveIcon')[i].setAttribute('class', 'moveIcon fa fa-arrows-alt');
      }
      $('.sorted_table').sortable('enable');
      $('#movement')[0].innerHTML = desactivar;
      $('#movement')[0].setAttribute('class', deactive_color);
    }
    else if ($('#movement')[0].innerHTML == desactivar){
      for (var i=0; i < $('.moveIcon').length; i++){
        $('.moveIcon')[i].setAttribute('class', 'moveIcon');
      }
      $('.sorted_table').sortable('disable');
      $('#movement')[0].innerHTML = activar;
      $('#movement')[0].setAttribute('class', active_color);
      $('#myForm').submit();
    }
  });
})
</script>
{% endblock %}
{% block plugin_css %}
<link rel="stylesheet" href="{% static 'web/global/css/jquery-sortable/jquery-sortable.css' %}">
<link href="{% static 'web/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'web/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'web/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'web/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'web/global/plugins/clockface/css/clockface.css' %}" rel="stylesheet" type="text/css">

{% endblock %}

web-service/webumvral/web/templates/web/course_students.html
{% extends "web/base_list.html" %}
{% load static %}
{% block title %}
Mis alumnos
{% endblock %}
{% block breadcrumb %}
<li>
  <a href="{% url 'web:course_list' %}"><span>Cursos</span></a>
  <i class="fa fa-angle-right"></i>
</li>
<li>
  <a href="{% url 'web:course_read' course.pk %}"><span> {{course.name}} </span></a>
  <i class="fa fa-angle-right"></i>
</li>
<li>
  <a href="{% url 'web:course_students' course.pk %}"><span> Mis Alumnos </span></a>
  <i class="fa fa-angle-right"></i>
</li>
{% endblock %}
{% block page_actions %}
<a href="{% url 'web:course_invite' course.pk %}" class="btn btn-fit-height default" role="button">
  <i class="icon-plus"></i>
  Invitar Alumno
</a>

{% endblock %}
{% block columns %}
<th>
  <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
      <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
      <span></span>
  </label>
</th>
<th>Nombre</th>
<th>Correo</th>
<th>Acciones</th>
{% endblock %}

{% block javascript %}
<script>
moment.locale("es");

var render_checkbox = function(student_id) {
  return `<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
            <input type="checkbox" class="checkboxes" name="selected_user"
                   value="${student_id}" />
            <span></span>
          </label>`;
};
var render_options = function(student_id, sprofile_id, course_id, user_id, course_name){
	var url1 = "{% url 'web:profile' 0 %}".replace('0', sprofile_id);
  var url2 = "{% url 'web:msg_direct' 0 %}".replace('0', user_id);
  var url3 = "{% url 'web:course_ban' 88888888 99999999 %}".replace('88888888', course_id).replace('99999999', student_id);
  return `<div class="btn-group">
            <button class="btn btn-xs orange dropdown-toggle" type="button"
                    data-toggle="dropdown" aria-expanded="false">
              ADMINISTRAR
              <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu pull-right" role="menu">
            <li>
              <a href="${url1}">
              <i class="icon-user"></i> Ver perfil </a>
            </li>
              <li class="divider" role="separator"></li>
              <li>
                <a href="${url3}">
                <i class="icon-ban"></i> Desmatricular alumno </a>
              </li>
            </ul>
          </div>`
};
var render_name = function(sprofile_id, name){
	var url = "{% url 'web:student_courseprofile' 888888888 99999999 %}".replace('888888888','{{course.pk}}').replace('99999999',sprofile_id)
	return `<a href="${url}"> ${name} </a>`
}
$(document).ready(function() {
		var course_id = "{{course.pk}}";
    var course_name = "{{course.name}}";
    var user_id = "{{request.user.profile.pk}}";
    var dt_table = $('#table').DataTable({
			processing: true,
			serverSide: true,
			language: {
				url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
			},
      order: [[ 0, "asc" ]],
      columnDefs: [
				{
						targets: 0,
						orderable: false,
						render: function (data, type, row){
							checkbox = render_checkbox(row[0]);
							return checkbox;
						}
				},
        {
	          name: 'Nombre Completo',
	          orderable: true,
	          searchable: true,
	          targets: 1,
						render: function(data, type, row){
							return render_name(row[3], row[1])
						}
        },
        {
            name: 'Correo',
            orderable: true,
            searchable: true,
            targets: 2,
						render: function(data, type, row){
							return row[2]
						}
        },
        {
            orderable: false,
            searchable: false,
            targets: 3,
						render: function(data, type, row){
							return render_options(row[0], row[3], course_id, user_id, course_name);
						}
				},
      ],
      searching: true,
      stateSave: true,
			ajax: '{% url "web:course_student_list_json" %}'+'?course_id='+course_id,
      data: {'course_id': course_id}
    });
});
</script>
{% endblock %}